import { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import Script from 'next/script'
const dm_sans = DM_Sans({
  weight: ['400', '500', '700', '400', '500', '700'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  metadataBase: new URL('https://tendrs.ai/'),
  title: 'Tendrs.AI - RFPs Redefined & simplified for next Generation',
  description:
    'Discover and bid on proposals that align with your services, post your needs for competitive bids, verify company details in one place, and explore innovative startups and success stories easily.',
  keywords: [
    "RFPs",
    "Bidding",
    "Proposals",
    "Services",
    "Competitive bids",
    "Company verification",
    "Startups",
    "Success stories",
    "Simplified RFPs",
    "Innovation",
    "Next generation",
    "Tendrs.AI",
    "Discovery platform",
    "Service alignment",
    "Company details",
    "Post needs",
    "Explore startups",
    "Simplified bidding process",
    "Competitive bidding",
    "Proposal discovery",
    "Bid management",
    "Bid optimization",
    "Procurement",
    "Contracting",
    "Marketplace",
    "Vendor management",
    "Request for quotations",
    "RFQs",
    "Proposal management",
    "Bid evaluation",
    "Supplier selection",
    "Contract management",
    "Bid matching",
    "Bid analytics",
    "Proposal submission",
    "Vendor verification",
    "Bid tracking",
    "Bidding platform",
    "Proposal platform",
    "Contract negotiation",
    "Project procurement",
    "Supplier diversity",
    "Sourcing solutions",
    "Bid aggregation",
    "Sourcing platform",
    "Vendor screening",
    "Proposal review",
    "Bid comparison",
    "Supplier qualification",
    "Procurement software",
    "Bid process",
    "RFx management",
    "Vendor qualification",
    "Request for information",
    "RFX process",
    "Proposal evaluation",
    "Bid monitoring",
    "Vendor evaluation",
    "Bid collaboration",
    "Procurement platform",
    "Contract bidding",
    "Contract lifecycle management",
    "Vendor selection",
    "Proposal tracking",
    "Request for tender",
    "Bid negotiation",
    "Supplier management",
    "RFP software",
    "Bid platform",
    "Procurement analytics",
    "Supplier evaluation",
    "Contract negotiation",
    "Proposal generation",
    "Bid response",
    "Contract compliance",
    "Bid portal",
    "Contract lifecycle management",
    "Request for bid",
    "Proposal collaboration",
    "Supplier monitoring",
    "Bid optimization",
    "Procurement process",
    "Vendor onboarding",
    "RFP management",
    "Bid automation",
    "Contract monitoring",
    "Bid submission",
    "Proposal automation",
    "Contract tracking",
    "Bid scoring",
    "Vendor portal",
    "RFP platform",
    "Bid assessment",
    "Procurement management",
    "Supplier portal",
    "Contract analysis",
    "Bid review",
    "Vendor management system",
    "Proposal scoring",
    "Bid management software",
    "Sourcing and procurement",
    "Supplier risk management",
    "Contract negotiation software",
    "Proposal management software",
    "Bid management system",
    "Supplier relationship management",
    "Bid tracking software",
    "RFP response software",
    "Vendor risk management",
    "Contract lifecycle software",
    "Proposal tracking software",
    "RFP software solutions",
    "Procurement management software",
    "Contract management software",
    "Bid response software",
    "RFX software",
    "Vendor performance management",
    "Bid analytics software",
    "Contract management system",
    "Proposal generation software",
    "RFP response management",
    "Procurement analytics software",
    "Supplier performance management",
    "RFP automation",
    "Bid evaluation software",
    "Vendor performance tracking",
    "Proposal evaluation software",
    "RFP management software",
    "Contract compliance software",
    "Bid management tools",
    "Procurement platform software",
    "Vendor evaluation software",
    "Proposal tracking system",
    "RFP bid software",
    "Bid management platform",
    "Procurement optimization",
    "Contract lifecycle management software",
    "Proposal automation software",
    "Bid tracking system",
    "RFX management software",
    "Vendor management software",
    "Contract negotiation tools",
    "RFP solution",
    "Bid response management",
    "Procurement software solutions",
    "RFP tracking software",
    "Proposal submission software",
    "Bid scoring software",
    "RFP proposal software",
    "Procurement automation software",
    "Vendor onboarding software",
    "Bid management solutions",
    "Proposal response software",
    "Contract management tools",
    "RFP response automation",
    "Procurement system software",
    "Bid response management software",
    "Proposal management tools",
    "RFX management system",
    "Vendor risk assessment",
    "Bid proposal software",
    "RFP response management software",
    "Procurement automation solutions",
    "Bid proposal management software",
    "RFP response tracking",
    "Vendor risk assessment software",
    "Bid response tracking",
    "RFP response tracking software",
    "Proposal response management",
    "Procurement system solutions",
    "RFP generation software",
    "Bid request software",
    "RFP response system",
    "Procurement analytics tools",
    "Bid management solutions",
    "RFX response software",
    "Proposal generation tools",
    "RFP automation software",
    "Procurement sourcing software",
    "Bid request management",
    "RFP generation tools",
    "Bid response system",
    "RFX response management",
    "Proposal request software",
    "RFP response system software",
    "Bid request management software",
    "Proposal response software",
    "Bid request system",
    "RFP response management system",
    "RFX response management software",
    "Bid request management system",
    "Proposal request management software",
    "Bid request tracking software",
    "RFP request software",
    "Bid request tracking system",
    "RFP request management software",
    "Bid request tracking",
    "RFX request software",
    "RFP request management system",
    "Bid request tracking software",
    "RFX request management software",
    "RFP request tracking",
    "Bid request system software",
    "RFX request management system",
    "RFP request tracking software",
    "Bid request system",
    "RFX request tracking software",
    "RFP request system software",
    "Bid request system tracking",
    "RFX request system software",
    "RFP request system tracking",
    "Bid request system management",
    "RFX request system tracking",
    "RFP request system management",
    "Bid request system software management",
    "RFX request system management",
    "RFP request system software management"

  ],
  abstract: 'Tendrs.AI is a discovery platform for RFPs, proposals, and services. Discover and bid on proposals that align with your services, post your needs for competitive bids, verify company details in one place, and explore innovative startups and success stories easily.',
  applicationName: 'Tendrs.AI',
  category: 'Business',
  robots: 'index, follow',
  openGraph: {
    type: 'website',
    images: [{ url: '/Banner.jpg' }]
  },
  twitter: {
    images: [{ url: '/Banner.jpg' }]
  }
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script
        strategy="lazyOnload"
        src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
      />

      <Script id="google-analytics-script" strategy="lazyOnload">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}', {
          page_path: window.location.pathname,
          });
    `}
      </Script>
      <body className={dm_sans.className}>{children}</body>
    </html>
  )
}
